package day38_exception;

public class ExceptionDemo_7 {

	public static void main(String[] args) {
		// we can use try catch block in nested way as much as requirements
		try {						
			
			
			
		}
		catch(Exception e ) {
			
			
		}
		finally {
			
			
			
		}
		
		
	}

}
